#include "SpectralModel.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace yk::spectral {
SpectralTransmissionModel::SpectralTransmissionModel(const std::vector<MaterialSpec>& m,const std::vector<SpectrumPoint>& s,const IMassAttenuationProvider& a,const DetectorResponseConfig& e):materials_(m),spectrum_(s),attenuation_(a),detector_response_(e){std::vector<double> en;for(auto& p:s)en.push_back(p.energy_keV);for(auto& x:m){std::vector<double> v;std::string err;if(!a.query(x,en,v,err))throw std::runtime_error(x.name+": "+err);mass_attenuation_.emplace(x.label,std::move(v));}}
SpectralResult SpectralTransmissionModel::simulate(const std::unordered_map<std::uint8_t,double>& paths) const {SpectralResult r;for(auto& p:spectrum_)r.incident_intensity+=p.fluence_per_keV_cm2_mAs_at_1m*p.bin_width_keV;if(r.incident_intensity<=0)throw std::runtime_error("incident spectrum fluence must be positive");for(size_t e=0;e<spectrum_.size();++e){double exponent=0;for(auto& m:materials_){auto i=paths.find(m.label);if(i!=paths.end())exponent+=i->second*m.density_g_cm3*mass_attenuation_.at(m.label)[e];}r.transmitted_intensity+=spectrum_[e].fluence_per_keV_cm2_mAs_at_1m*spectrum_[e].bin_width_keV*std::exp(-exponent);}r.line_integral=-std::log(std::max(r.transmitted_intensity,1e-30)/r.incident_intensity);return r;}
SpectralResult SpectralTransmissionModel::simulate(const std::vector<double>& paths) const {if(paths.size()!=materials_.size())throw std::runtime_error("material path count mismatch");std::unordered_map<std::uint8_t,double> mapped;for(size_t i=0;i<materials_.size();++i)mapped.emplace(materials_[i].label,paths[i]);return simulate(mapped);}
std::vector<double> SpectralTransmissionModel::detectorMassAttenuation(const DetectorLayerConfig& layer) const {MaterialSpec material;material.name=layer.name;material.preset=layer.preset;material.density_g_cm3=layer.density_g_cm3;std::vector<double> energies;for(const auto& point:spectrum_)energies.push_back(point.energy_keV);std::vector<double> values;std::string error;if(!attenuation_.query(material,energies,values,error))throw std::runtime_error(layer.name+": "+error);return values;}
}
