file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(nx 65)
set(ny 65)
set(nz 17)
set(voxel_mm 1.0)
if(TYPE MATCHES "tungsten_wire|gold_foil")
    set(voxel_mm 0.01)
endif()
if(TYPE STREQUAL "low_contrast")
    set(nx 288)
    set(ny 288)
    set(nz 21)
    set(voxel_mm 0.25)
endif()
set(raw "${OUTPUT_DIR}/${TYPE}.raw")
execute_process(
    COMMAND "${GENERATOR}" "${TYPE}" "${raw}" "${nx}" "${ny}" "${nz}" "${voxel_mm}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "${TYPE} generation failed: ${stdout}${stderr}")
endif()
math(EXPR expected_size "${nx} * ${ny} * ${nz}")
file(SIZE "${raw}" raw_size)
if(NOT raw_size EQUAL expected_size)
    message(FATAL_ERROR "${TYPE} RAW size is ${raw_size}, expected ${expected_size}")
endif()
set(metadata "${raw}.toml")
if(NOT EXISTS "${metadata}")
    message(FATAL_ERROR "${TYPE} did not produce TOML metadata")
endif()
file(READ "${metadata}" toml)
foreach(required IN ITEMS "[phantom]" "label_volume =" "[[projection.materials]]")
    string(FIND "${toml}" "${required}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "${TYPE} TOML is missing: ${required}")
    endif()
endforeach()
if(EXISTS "${raw}.json")
    message(FATAL_ERROR "${TYPE} unexpectedly produced JSON metadata")
endif()
