schema_version = 2

[workflow]
mode = "project_and_reconstruct"

[projection]
label_volume = "../../inputs/generated/water-cylinder-200mm-pmma5mm.raw"
spectrum_file = "../../spectra/120kVp_12deg_1000mm_2mmAl.spec"
xcom_data_directory = "../../../../thirdparty/nist_xcom/data"
output_file = "../../outputs/projections/water-cylinder-200mm-pmma5mm-fdk-focal-1p2x0p9-1536x256x540-f32.raw"
energy_output_file = "../../outputs/projections/water-cylinder-200mm-pmma5mm-fdk-focal-1p2x0p9-energy-1536x256x540-f32.raw"
apply_geometry_flux = true

[projection.sampling]
samples_per_pixel = 50
spatial_seed = 12345

[projection.focal_spot]
enabled = true
size_u_mm = 1.2
size_v_mm = 0.9

[geometry]
kind = "flat_cbct"
views = 540
views_per_turn = 540
rotation_direction = 1
detector_u = 1536
detector_v = 256
pixel_u_mm = 0.53
pixel_v_mm = 0.53
sid_mm = 709.0
sdd_mm = 1143.0
offset_u_mm = 0.0
offset_n_mm = 0.0
offset_v_mm = 0.0
source_offset_x_mm = 0.0
source_offset_y_mm = 0.0
source_offset_z_mm = 0.0
start_angle_rad = 0.0
pitch_mm_per_turn = 0.0
start_z_mm = 0.0
volume_x = 401
volume_y = 401
volume_z = 256
voxel_x_mm = 0.5
voxel_y_mm = 0.5
voxel_z_mm = 0.5
phantom_offset_x_mm = 0.0
phantom_offset_y_mm = 0.0
phantom_offset_z_mm = 0.0
reconstruction_volume_x = 1024
reconstruction_volume_y = 1024
reconstruction_volume_z = 30
reconstruction_voxel_x_mm = 0.33
reconstruction_voxel_y_mm = 0.33
reconstruction_voxel_z_mm = 1.0
reconstruction_offset_x_mm = 0.0
reconstruction_offset_y_mm = 0.0
reconstruction_offset_z_mm = 0.0

[[projection.materials]]
label = 1
name = "water"
formula = "H2O"
density_g_cm3 = 1.0

[[projection.materials]]
label = 2
name = "pmma"
formula = "C5H8O2"
density_g_cm3 = 1.18

[reconstruction]
type = "analytic"
output_volume_file = "../../outputs/reconstructions/water-cylinder-200mm-pmma5mm-fdk-focal-1p2x0p9-1024x1024x30-f32.raw"
slice_prefix = "../../outputs/images/water-cylinder-200mm-pmma5mm-fdk-focal-1p2x0p9-1024x1024x30"

[reconstruction.analytic]
pipeline = "fdk"
filter = "ramlak"
chunk_views = 8

