schema_version = 2

[workflow]
mode = "project_and_reconstruct"

[projection]
label_volume = "../../../inputs/generated/tungsten-bead-synchronized-ring-100mm-3mm-dual-marker5-12beads-0p2mm.raw"
spectrum_file = "../../../spectra/120kVp_12deg_1000mm_2mmAl.spec"
xcom_data_directory = "../../../../../thirdparty/nist_xcom/data"
output_file = "../../../outputs/calibration/synchronized-ring-12-dual-marker-1024x1024x360-ou5-ov10-tu1-tv2-tn3-soy10-soz5-px10-py15-pz20-prx1-pry2-prz3-projection.raw"
apply_geometry_flux = true
save_metadata = false

[projection.sampling]
samples_per_pixel = 5
spatial_seed = 12345

[projection.focal_spot]
enabled = false
size_u_mm = 0.0
size_v_mm = 0.0

[geometry]
kind = "flat_cbct"
views = 360
views_per_turn = 360
rotation_direction = 1
detector_u = 1024
detector_v = 1024
pixel_u_mm = 0.417
pixel_v_mm = 0.417
sid_mm = 440.0
sdd_mm = 770.0
offset_u_mm = 2.085
offset_n_mm = 0.0
offset_v_mm = 4.17
tilt_u_rad = 0.0174532925199433
tilt_v_rad = 0.0349065850398866
tilt_n_rad = 0.0523598775598299
source_offset_x_mm = 0.0
source_offset_y_mm = 10.0
source_offset_z_mm = 5.0
start_angle_rad = 0.0
pitch_mm_per_turn = 0.0
start_z_mm = 0.0
volume_x = 550
volume_y = 550
volume_z = 900
voxel_x_mm = 0.2
voxel_y_mm = 0.2
voxel_z_mm = 0.2
phantom_offset_x_mm = 10.0
phantom_offset_y_mm = 15.0
phantom_offset_z_mm = 20.0
phantom_rotation_x_rad = 0.0174532925199433
phantom_rotation_y_rad = 0.0349065850398866
phantom_rotation_z_rad = 0.0523598775598299
reconstruction_volume_x = 768
reconstruction_volume_y = 768
reconstruction_volume_z = 600
reconstruction_voxel_x_mm = 0.30
reconstruction_voxel_y_mm = 0.30
reconstruction_voxel_z_mm = 0.30
reconstruction_offset_x_mm = 0.0
reconstruction_offset_y_mm = 0.0
reconstruction_offset_z_mm = 0.0

[reconstruction]
type = "analytic"
input_projection_file = "../../../outputs/calibration/synchronized-ring-12-dual-marker-1024x1024x360-ou5-ov10-tu1-tv2-tn3-soy10-soz5-px10-py15-pz20-prx1-pry2-prz3-projection.raw"
output_volume_file = "../../../outputs/calibration/synchronized-ring-12-dual-marker-1024x1024x360-ou5-ov10-tu1-tv2-tn3-soy10-soz5-px10-py15-pz20-prx1-pry2-prz3-recon-768x768x600.raw"
slice_prefix = "../../../outputs/calibration/synchronized-ring-12-dual-marker-1024x1024x360-ou5-ov10-tu1-tv2-tn3-soy10-soz5-px10-py15-pz20-prx1-pry2-prz3"
save_slices = false

[reconstruction.analytic]
pipeline = "fdk"
filter = "ramlak"
chunk_views = 32

[[projection.materials]]
label = 1
name = "pmma_support"
formula = "C5H8O2"
density_g_cm3 = 1.18

[[projection.materials]]
label = 100
name = "tungsten"
formula = "W"
density_g_cm3 = 19.25

